server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    hostname: api-gateway
    nonSecurePort: ${server.port}
    preferIpAddress: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: aplicativo_movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/movies/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: moviesService
                fallbackUri: forward:/fallback/movies
        - id: aplicativo_catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalog
  zipkin:
    base-url: http://zipkin:9411
    enabled: true

queue:
  movie:
    name: MovieQueue

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true
    info:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: API Gateway
  svc:
    intanceid: ${eureka.instance.instance-id}
    port: ${server.port}
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    org.springframework.boot.autoconfigure.web: INFO
    reactor.netty: INFO




#server:
#  port: 8080
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://eurekaserver:8761/eureka
#  instance:
#    hostname: localhost
#    nonSecurePort: ${server.port}
#    preferIdAddress: true
#
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      discovery:
#         locator:
#           enabled: true
##           lower-case-service-id: true
#      routes:
#        - id: aplicativo_movie-service
#          uri: lb://movie-service
#          predicates:
#            - Path=/api/movies/**
#          filters:
#            - StripPrefix=2
#            - name: CircuitBreaker
#              args:
#                name: moviesService
#                fallbackUri: forward:/fallback/movies
#        - id: aplicativo_catalog-service
#          uri: lb://catalog-service
#          predicates:
#            - Path=/api/catalog/**
#          filters:
#            - StripPrefix=2
#            - name: CircuitBreaker
#              args:
#                name: catalogService
#                fallbackUri: forward:/fallback/catalog
#  zipkin:
#    base-url: http://zipkin:9411
#    enabled: true
#  rabbitmq:
#    username: guest
#    password: guest
#    host: rabbitmq3
#    port: 5672
#
#queue:
#  movie:
#    name: MovieQueue
#
#info:
#  app:
#    name: ${spring.application.name}
#    version: 1.0.0
#    description: API Gateway
#  svc:
#    intanceid: ${eureka.instance.instance-id}
#    port: ${server.port}
#
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: info
#  info:
#    env:
#      enabled: true
#  gateway:
#    env:
#      enabled: true
#  endpoint:
#    info:
#      enabled: true
#    gateway:
#      enabled: true



