server:
  port: 8761

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411
    enabled: true

eureka:
  instance:
    hostname: eurekaserver
    preferIpAddress: false

  client:
    fetch-registry: false
    register-with-eureka: false
    
